name = "atenra-waitlist"
compatibility_date = "2026-02-04"
account_id = "aced7fa820f99073b64763a141e1015a"
workers_dev = true
main = "src/worker.js"

[build]
command = "npm run build"
cwd = "./"

[build.upload]
format = "modules"
